-- 코드를 입력하세요
SELECT M.MEMBER_NAME AS MEMBER_NAME, R.REVIEW_TEXT AS REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d')AS REVIEW_DATE
FROM MEMBER_PROFILE M 
Inner JOIN REST_REVIEW R ON R.MEMBER_ID = M.MEMBER_ID
WHERE R.MEMBER_ID = (
SELECT MEMBER_ID FROM REST_REVIEW
    GROUP BY REST_REVIEW.MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1
)
ORDER BY R.REVIEW_DATE ASC, R.REVIEW_TEXT ASC