-- 코드를 입력하세요
SELECT B.CATEGORY as CATEGORY, sum(BS.SALES) as TOTAL_SALES
FROM BOOK B
INNER JOIN BOOK_SALES BS ON B.BOOK_ID = BS.BOOK_ID
WHERE BS.sales_date >= '2022-01-01' AND BS.sales_date <= '2022-01-31'
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY ASC